"use client"
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./__component/Navbar/Navbar";
import Footer from "./__component/Footer/Footer";
import { Provider } from "react-redux";
import { store } from "./rtk/store";
import { ToastContainer } from "react-toastify";

const nunito = Nunito({ subsets: ["latin"],
weight:"400"
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
        <ToastContainer />
        {children}
        <Footer />
      </body>
    </html>
    </Provider>
  );
}
